i1135: Output PEM format public key
vimc/montagu-cert-tool pull request #2
Opened 2018-01-08 13:08 UTC by richfitz

2018-01-08 13:08 UTC, richfitz commented
This is required to support deploy work for VIMC-1135 in the montagu repo

2018-01-09 10:46 UTC, hillalex requested changes
One tiny edit needed

2018-01-09 10:46 UTC, littledice commented on src/main/kotlin/org/vaccineimpact/certificate_tool/GenerateKeyPair.kt
> +        println("Wrote public PEM key to $outputPath/public_key.der")
The line that's printed has the wrong file extension at the end!

2018-01-10 19:05 UTC, hillalex approved these changes

2018-01-10 19:05 UTC, merged